# espanso match file - PUBLIC matches only
# Sensitive matches are in secrets.yml (encrypted with agenix)
# For a complete introduction, visit the official docs at: https://espanso.org/docs/

matches:
  # Symbols
  - trigger: ":euro"
    replace: "\u20ac"

  - trigger: ":div"
    replace: <div>$|$</div>