# espanso match file - WIT (Wentworth) related matches
# Uses witw variable from secrets.yml (automatically loaded from match directory)

matches:
  - trigger: ">cc1000"
    replace: |
      /* @formatter:off
       *
       * © {{fl_name}} <{{school_email}}> ({{witw}})
       * {{school}}
       * COMP 1000 - Fall 2025
       * Professor Micah Schuster <schusterm@wit.edu>
       *
       * $|$
       *
       * @formatter:on
       */
  - trigger: ">pe1000"
    replace: "schusterm@wit.edu"

  - trigger: ">cc1050"
    replace: |
      /* @formatter:off
       *
       * © {{fl_name}} <{{school_email}}> ({{witw}})
       * {{school}}
       * COMP 1050 - Spring 2026
       * Professor Dave Rosenberg <rosenbergd@wit.edu>
       *
       * $|$
       *
       * @formatter:on
       */
  - trigger: ">pe1050"
    replace: "rosenbergd@wit.edu"

  - trigger: ">cc1200"
    replace: |
      /* @formatter:off
       *
       * © {{fl_name}} <{{school_email}}> ({{witw}})
       * {{school}}
       * COMP 1200 - Spring 2026
       * Professor Koorosh Firouzbakht <firouzbakhtk@wit.edu>
       *
       * $|$
       *
       * @formatter:on
       */
  - trigger: ">pe1200"
    replace: "firouzbakhtk@wit.edu"

  - trigger: ">ccCSAS2000"
    replace: |
      /* @formatter:off
       *
       * © {{fl_name}} <{{school_email}}> ({{witw}})
       * {{school}}
       * CSAS 2000 - Spring 2026
       * Professor Ella Howard <howarde@wit.edu>
       *
       * $|$
       *
       * @formatter:on
       */
  - trigger: ">peCSAS2000"
    replace: "howarde@wit.edu"
