# espanso match file - WIT (Wentworth) related matches
# Imports secrets.yml for sensitive variables (my_id)

imports:
  - "secrets.yml"

global_vars:
  - name: my_name
    type: echo
    params:
      echo: "Jasper Mayone"
  - name: my_email
    type: echo
    params:
      echo: "mayonej@wit.edu"
  - name: school
    type: echo
    params:
      echo: "Wentworth Institute of Technology"

matches:
  - trigger: ">cc1000"
    replace: |
      /* @formatter:off
       *
       * © {{my_name}} <{{my_email}}> ({{my_id}})
       * {{school}}
       * COMP 1000 - Fall 2025
       * Professor Micah Schuster <schusterm@wit.edu>
       *
       * $|$
       *
       * @formatter:on
       */
  - trigger: ">pe1000"
    replace: "schusterm@wit.edu"

  - trigger: ">cc1050"
    replace: |
      /* @formatter:off
       *
       * © {{my_name}} <{{my_email}}> ({{my_id}})
       * {{school}}
       * COMP 1050 - Spring 2026
       * Professor Dave Rosenberg <rosenbergd@wit.edu>
       *
       * $|$
       *
       * @formatter:on
       */
  - trigger: ">pe1050"
    replace: "rosenbergd@wit.edu"

  - trigger: ">cc1200"
    replace: |
      /* @formatter:off
       *
       * © {{my_name}} <{{my_email}}> ({{my_id}})
       * {{school}}
       * COMP 1200 - Spring 2026
       * Professor Koorosh Firouzbakht <firouzbakhtk@wit.edu>
       *
       * $|$
       *
       * @formatter:on
       */
  - trigger: ">pe1200"
    replace: "firouzbakhtk@wit.edu"

  - trigger: ">ccCSAS2000"
    replace: |
      /* @formatter:off
       *
       * © {{my_name}} <{{my_email}}> ({{my_id}})
       * {{school}}
       * CSAS 2000 - Spring 2026
       * Professor Ella Howard <howarde@wit.edu>
       *
       * $|$
       *
       * @formatter:on
       */
  - trigger: ">peCSAS2000"
    replace: "howarde@wit.edu"
